# Generated by Django 3.2.19 on 2023-07-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0065_auto_20230608_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='serologiaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSerologia', models.CharField(max_length=40)),
                ('serologia', models.CharField(max_length=40)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente', unique=True)),
            ],
        ),
    ]
