# Generated by Django 3.2.19 on 2023-07-12 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0066_auto_20230712_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serologiapaciente',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente'),
        ),
    ]
