# Generated by Django 3.2.19 on 2023-07-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0067_alter_serologiapaciente_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='examenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(blank=True, max_length=4, null=True)),
                ('periodo', models.CharField(blank=True, max_length=6, null=True)),
                ('area', models.CharField(blank=True, max_length=40, null=True)),
                ('servicio', models.CharField(blank=True, max_length=20, null=True)),
                ('actividad', models.CharField(blank=True, max_length=40, null=True)),
                ('subactividad', models.CharField(blank=True, max_length=40, null=True)),
                ('acto_medico', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_atencion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_solicitud', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_cita', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_resultado', models.CharField(blank=True, max_length=10, null=True)),
                ('num_solicitud', models.CharField(blank=True, max_length=10, null=True)),
                ('dni_solicita', models.CharField(blank=True, max_length=10, null=True)),
                ('prof_solicita', models.CharField(blank=True, max_length=100, null=True)),
                ('tipexamen', models.CharField(blank=True, max_length=10, null=True)),
                ('arealab', models.CharField(blank=True, max_length=20, null=True)),
                ('sede', models.CharField(blank=True, max_length=20, null=True)),
                ('examen', models.CharField(blank=True, max_length=10, null=True)),
                ('descexamen', models.CharField(blank=True, max_length=200, null=True)),
                ('dni_profesional', models.CharField(blank=True, max_length=10, null=True)),
                ('profesional', models.CharField(blank=True, max_length=100, null=True)),
                ('dni_paciente', models.CharField(blank=True, max_length=15, null=True)),
                ('h_c', models.CharField(blank=True, max_length=10, null=True)),
                ('paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=50, null=True)),
                ('annos', models.CharField(blank=True, max_length=3, null=True)),
                ('meses', models.CharField(blank=True, max_length=2, null=True)),
                ('dias', models.CharField(blank=True, max_length=2, null=True)),
                ('sexo', models.CharField(blank=True, max_length=6, null=True)),
                ('tipo_paciente', models.CharField(blank=True, max_length=20, null=True)),
                ('cas_adscripcion', models.CharField(blank=True, max_length=6, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=10, null=True)),
                ('des_diagn', models.CharField(blank=True, max_length=100, null=True)),
                ('tip_diagn', models.CharField(blank=True, max_length=10, null=True)),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria_resul', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.CharField(blank=True, max_length=10, null=True)),
                ('usuario_registro', models.CharField(blank=True, max_length=20, null=True)),
                ('informe_resultado', models.CharField(blank=True, max_length=200, null=True)),
                ('orden_plantilla', models.CharField(blank=True, max_length=6, null=True)),
                ('desc_plantilla', models.CharField(blank=True, max_length=40, null=True)),
                ('valor_resultado', models.CharField(blank=True, max_length=20, null=True)),
                ('unidadvalor', models.CharField(blank=True, max_length=40, null=True)),
                ('observresultado', models.CharField(blank=True, max_length=40, null=True)),
                ('usario_modifica', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_modifica', models.CharField(blank=True, max_length=10, null=True)),
                ('centro_origen_solicitud', models.CharField(blank=True, max_length=4, null=True)),
                ('codresul_covid', models.CharField(blank=True, max_length=6, null=True)),
                ('resultado_covid', models.CharField(blank=True, max_length=40, null=True)),
                ('hora_registro', models.CharField(blank=True, max_length=20, null=True)),
                ('autogenerado', models.CharField(blank=True, max_length=20, null=True)),
                ('desc_topico', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loginAppHisar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contra', models.CharField(max_length=200)),
                ('estado', models.CharField(default=1, max_length=5)),
                ('tipoTrataPac', models.CharField(max_length=5)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='dpDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultrafil', models.IntegerField()),
                ('presArtSis', models.IntegerField()),
                ('presArtDias', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('userReg', models.CharField(max_length=40)),
                ('fechaReg', models.DateField(auto_now_add=True)),
                ('imagenOriSalida', models.FileField(blank=True, null=True, upload_to='media/imgOriSal')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
            ],
        ),
    ]
