# Generated by Django 3.2.19 on 2023-07-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0068_auto_20230718_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpdiario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente'),
        ),
    ]
