# Generated by Django 3.2.19 on 2023-07-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0069_auto_20230724_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='asispacdiario',
            name='tipoAsiste',
            field=models.CharField(blank=True, default='NORMAL', max_length=20, null=True),
        ),
    ]
