# Generated by Django 3.2.19 on 2023-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0070_auto_20230727_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asispacdiario',
            name='tipoAsiste',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
    ]
