# Generated by Django 3.2.19 on 2023-07-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0071_auto_20230727_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asispacdiario',
            name='tipoAsiste',
            field=models.CharField(blank=True, default='NORMAL', max_length=20, null=True),
        ),
    ]
