# Generated by Django 3.2.19 on 2023-07-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0072_auto_20230727_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asispacdiario',
            name='tipoAsiste',
        ),
    ]
