# Generated by Django 3.2.19 on 2023-07-31 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0073_auto_20230727_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='asisPacDiarioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=100)),
                ('estadoAsistencia', models.CharField(max_length=30)),
                ('usuario_reg', models.CharField(max_length=150)),
                ('fecha_reg', models.DateField(auto_now=True)),
                ('validacionAsistencia', models.CharField(max_length=150, unique=True)),
                ('cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.cas')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
            ],
        ),
    ]
