# Generated by Django 3.2.19 on 2023-08-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0074_auto_20230731_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='asispacdiarioadicional',
            name='motivo',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
