# Generated by Django 3.2.19 on 2023-08-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0075_auto_20230801_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='asispacdiarioadicional',
            name='sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
