# Generated by Django 3.2.19 on 2023-09-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0076_auto_20230818_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ubigeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigeo_reniec', models.CharField(max_length=10)),
                ('ubigeo_inei', models.CharField(max_length=10)),
                ('codDepartamento_inei', models.CharField(max_length=10)),
                ('departamento', models.CharField(max_length=50)),
                ('codProvincia_inei', models.CharField(max_length=10)),
                ('provincia', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
            ],
        ),
    ]
