# Generated by Django 3.2.19 on 2023-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0077_auto_20230913_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='pacienteGeoTem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('hospital', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
                ('distrito', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
                ('serologia', models.CharField(max_length=20)),
            ],
        ),
    ]
