# Generated by Django 3.2.19 on 2023-09-14 16:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0078_auto_20230914_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientegeotem',
            name='cordePac',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Point(longitude latitude)', null=True, srid=4326, verbose_name='Location in Map'),
        ),
    ]
