# Generated by Django 3.2.19 on 2023-09-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0079_auto_20230914_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientegeotem',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pacientegeotem',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientegeotem',
            name='longitud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientegeotem',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientegeotem',
            name='turno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
