# Generated by Django 3.2.19 on 2023-09-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0085_auto_20230914_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientelocalizacion',
            name='cas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.cas'),
        ),
        migrations.AlterField(
            model_name='pacientelocalizacion',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente'),
        ),
    ]
