# Generated by Django 3.2.19 on 2023-11-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0086_auto_20230914_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='asispacdiarioadicional',
            name='casAsd',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asispacdiarioadicional',
            name='vigSeguro',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
