# Generated by Django 3.2.19 on 2023-11-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0087_auto_20231109_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='asispacdiario',
            name='casAsd',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asispacdiario',
            name='vigSeguro',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        )
    ]
