# Generated by Django 3.2.19 on 2023-11-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0088_auto_20231109_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asispacdiario',
            name='casAsd',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='asispacdiario',
            name='vigSeguro',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='asispacdiarioadicional',
            name='casAsd',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='asispacdiarioadicional',
            name='vigSeguro',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
