# Generated by Django 3.2.19 on 2023-11-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0089_auto_20231109_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asigcupospac',
            name='fechaAsigCupo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
