# Generated by Django 3.2.19 on 2023-11-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0090_auto_20231121_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='asigcupospac',
            name='estado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asigcupospac',
            name='fechaTerminoCupo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asigcupospac',
            name='usuario_reg_termino',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
