# Generated by Django 3.2.19 on 2023-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0092_auto_20231121_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='asispacdiario',
            name='estadoAcredi',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
