# Generated by Django 3.2.19 on 2024-01-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0093_auto_20231121_1019'),
    ]

    operations = [
    ]
