# Generated by Django 3.2.19 on 2024-01-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0094_auto_20240123_1447'),
    ]

    operations = [
    ]
