# Generated by Django 3.2.19 on 2024-01-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0095_listaespera_telefonodos'),
    ]

    operations = [
    ]
