# Generated by Django 3.2.19 on 2024-01-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0096_auto_20240123_1612'),
    ]

    operations = [
       
    ]
