# Generated by Django 3.2.19 on 2024-01-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0098_auto_20240124_0936'),
    ]

    operations = [
    ]
