# Generated by Django 3.2.19 on 2024-01-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0099_auto_20240124_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='correos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.cas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.usuario')),
            ],
        ),
    ]
