# Generated by Django 3.2.19 on 2024-01-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0100_auto_20240124_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.maestro'),
        )
    ]
